#!/bin/bash
min_signal_diff_for_switching=12

# Lets do a scan first
sudo /usr/bin/nmcli -t -f ssid,signal,rate,in-use dev wifi rescan

# And get the list of known networks
known_networks_info=$(/usr/bin/nmcli -t -f name connection show | sed -e 's/^Auto //g')

# What's the current network, yet?
current_network_name=$(/usr/bin/nmcli -t -f ssid,signal,rate,in-use dev wifi list | grep ':\*' | cut -d ':' -f1)
current_network_strength=$(/usr/bin/nmcli -t -f ssid,signal,rate,in-use dev wifi list | grep ':\*' | cut -d ':' -f2)

# Now see if we have a better network to switch to. Networks are sorted by signal strength so there's no need to check them all if the first signal's strength is not higher than current network's strength + min_signal_diff_for_switching.
while IFS= read -r network ; do
        network_name=$(echo $network | cut -d ':' -f1)
        network_strength=$(echo $network | cut -d ':' -f2)
        if [[ "$network_name" == "" ]]; then continue ; fi # MESH hotspots may appear with an non existent SSID so we skip them 
        if [[ "$known_networks_info" == *"$network_name"* ]]; then
                if [ $network_strength -ge $(($current_network_strength + 12)) ]; then
                        notification="Switching to network $network_name that has a better signal ($network_strength>$(($current_network_strength + 12)))"
                        echo $notification
                        notify-send "$notification"
                        sudo /usr/bin/nmcli device wifi connect "$network_name"
                        exit 0
                else
                        #echo "Network $network_name is well known but its signal's strength is not worth switching."
                        exit 0
                fi
        fi
done <<< "$(/usr/bin/nmcli -t -f ssid,signal,rate,in-use dev wifi list | grep -v "$current_network_name" | sort -nr -k2 -t':')"
