#! /bin/sh

### AUTOSTART ####
pgrep -x sxhkd > /dev/null || sxhkd &

#Composting
picom &

bash ~/.config/polybar/material/scripts/pywal.sh ~/Pictures/Wallpapers/224784.jpg
betterlockscreen -u ~/Pictures/Wallpapers &

bash ~/.config/polybar/launch.sh --hack &
nm-applet &

fusuma &

dunst &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^2' focus=on state=monocle
bspc rule -a google-chrome desktop='^2' state=monocle
# bspc rule -a kitty desktop='^1'
bspc rule -a mplayer2 state=floating
bspc rule -a Sunamu state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=fullscreen follow=on

#Use Pywal on bspwm
# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"

xdo lower -n polybar

xinput set-prop 11 332 1
xinput set-prop 11 316 1
setxkbmap -option caps:swapescape

sudo chmod 0664 /sys/class/backlight/intel_backlight/brightness
